---
title: "Generate Data and Test"
author: "Amos B. Elberg"
date: "2/7/2019"
output: html_document
params:
  N: 700
  S: 5
  P: 52
  F: 2
  periods_to_predict: 15
  period_scale: 52
  p: 2
  q: 2
  ar: 2
  nu: 3
  m0: .05
  s: 12
  use_sampled: F
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(magrittr)
library(ggplot2)
library(rethinking)
library(bayesplot)
library(tidybayes)
library(rstan)
library(ggplot2)
library(forcats)
library(purrr)
library(rethinking)
library(MASS)
library(tidyr)
library(stringr)
```

## Generate Price Series

```{r seed}
set.seed(1974)
periods_to_generate <- params$P + params$periods_to_predict
period_vline <- data.frame(xintercept=params$P)
```

```{r trends}
theta_trend <- abs(rcauchy(params$S, 0, 1)) / params$period_scale
omega_trend <- rlkjcorr(1, params$S)
alpha_trend <- abs(rnorm(params$S, 0, 1)) / params$period_scale
beta_trend <- pmin(abs(matrix(rnorm(params$S * params$ar, sd=0.1),  ncol=params$S)), .3) 
L_omega_trend <- t(chol(omega_trend))
L_Omega_trend <- crossprod(diag(theta_trend), L_omega_trend)
Omega_trend <- tcrossprod(L_Omega_trend)

nu <- mvrnorm(n=periods_to_generate, rep(0, params$S), Omega_trend)

delta <- list(
)

for (t in 1:nrow(nu)) {
  if (t == 1) delta <- c(delta, list(nu[1, ] + alpha_trend)) 
  else if (t <= params$ar) {
    past_delta <-  do.call(rbind, delta)
    beta <- beta_trend[(nrow(beta_trend) - t + 2):nrow(beta_trend), ]
    delta <- c(delta, list(
      alpha_trend + colSums(beta * past_delta - alpha_trend) + nu[t, ]
    ))
  } else {
    first_row <- length(delta) - params$ar + 1
    past_delta <- do.call(rbind, delta[first_row:(first_row + params$ar)])
    delta <- c(delta, list(
      alpha_trend + colSums(beta_trend * (past_delta - alpha_trend)) + nu[t, ]
    ))
  }
}

delta <- do.call(rbind, delta)
delta %>% data.frame() %>%
  set_colnames(paste("series", 1:params$S, sep="_")) %>%
  mutate(period = 1:n()) %>%
  gather(key="series", value="trend", -period) %>%
  ggplot(aes(x = period, y=trend, color=series)) + 
  geom_line(size=0.5, alpha=0.4) +
  geom_vline(data=period_vline, aes(xintercept=xintercept), color="red") +
  theme_minimal() + 
  ggtitle("Generated Trends")
```

```{r seasonality}
theta_season <- abs(rcauchy(params$S, scale=1)) / params$period_scale
w <- matrix(rnorm(params$S * periods_to_generate, sd=theta_season^2), byrow=T, ncol=params$S)
tau <- list()

for (t in 1:periods_to_generate) {
  if (t < params$s) tau <- c(tau, list(w[t, ]))
  else {
    prior_tau <- do.call(rbind, tau[(t - params$s + 1):(t-1)])
    tau <- c(tau, list(-colSums(prior_tau) + w[t, ]))
  }
}

tau <- do.call(rbind, tau)

tau %>% data.frame() %>%
  set_colnames(paste("series", 1:params$S, sep="_")) %>%
  mutate(period = 1:n()) %>%
  gather(key="series", value="seasonality", -period) %>%
  ggplot(aes(x = period, y=seasonality, color=series)) + 
  geom_line(size=0.5, alpha=0.4) +
  geom_vline(data=period_vline, aes(xintercept=xintercept), color="red") +
  theme_minimal() + 
  ggtitle("Generated Seasonality")

```

```{r cyclicality}
lambda <- runif(params$S, 0, pi)
rho <- runif(params$S, 0, 1)
theta_cycle <- abs(rcauchy(params$S, 0, .1)) / params$period_scale
kappa <- matrix(rnorm(params$S * periods_to_generate, sd = theta_cycle), byrow = T, ncol=params$S)
kappa_star <- matrix(rnorm(params$S * periods_to_generate, sd = theta_cycle), byrow = T, ncol=params$S)

omega <- list(
  kappa[1, ]
)
omega_star <- list(
  kappa_star[1, ]
)

for (t in 2:periods_to_generate) { 
  omega <- c(omega, list(
    (rho * cos(lambda) * omega[[t-1]][[1]]) + (rho * sin(lambda) * omega_star[[t-1]][[1]]) + kappa[t, ]
  ))
  omega_star <- c(omega_star, list(
    -(rho * sin(lambda) * omega[[t-1]][[1]]) + (rho * cos(lambda) * omega_star[[t-1]][[1]]) + kappa_star[t, ]
  ))
}

omega <- do.call(rbind, omega)

omega %>% data.frame() %>%
  set_colnames(paste("series", 1:params$S, sep="_")) %>%
  mutate(period = 1:n()) %>%
  gather(key="series", value="cyclicality", -period) %>% 
  ggplot(aes(x = period, y=cyclicality, color=series)) + 
  geom_line(size=0.5, alpha=0.4) +
  geom_vline(data=period_vline, aes(xintercept=xintercept), color="red") +
  theme_minimal() + 
  ggtitle("Generated Cyclicality")
```

```{r innovations}
theta_epsilon <- abs(rcauchy(params$S, 0, .1)) / params$period_scale
omega_epsilon <- rlkjcorr(1, params$S)
L_omega_epsilon <- t(chol(omega_epsilon))
L_Omega_epsilon <- crossprod(diag(theta_epsilon), L_omega_epsilon)
Omega_epsilon <- tcrossprod(L_Omega_epsilon)

epsilon <- mvrnorm(n=periods_to_generate, rep(0, params$S), Omega_epsilon)

epsilon %>% data.frame() %>%
  set_colnames(paste("series", 1:params$S, sep="_")) %>%
  mutate(period = 1:n()) %>%
  gather(key="series", value="innovation", -period) %>% 
  ggplot(aes(x = period, y=innovation, color=series)) + 
  geom_vline(data=period_vline, aes(xintercept=xintercept), color="red") +
  geom_line(size=0.5, alpha=0.4) +
  theme_minimal() + 
  ggtitle("Generated Innovations")
```

```{r assemble_price_series}
price_fluctuations <- delta + tau + omega + epsilon

starting_prices <- log1p(runif(params$S, 500, 2000))

prices <- rbind(starting_prices, price_fluctuations) %>%
  data.frame() %>%
  set_colnames(paste("series", 1:params$S, sep="_")) %>%
  mutate_all(cumsum) %>%
  dplyr::filter(row_number() != 1) %>% 
  mutate(period = 1:n())

prices %>%
  gather(key="series", value="log_price", -period) %>%
  mutate(price = exp(log_price) - 1) %>%
  ggplot(aes(x = period, y = price, color=series)) + 
  geom_line(size=0.5, alpha=0.7) + 
  geom_vline(data=period_vline, aes(xintercept=xintercept), color="red") +
  theme_minimal() + 
  ggtitle("Generated Price Series")
```


## Make Model And Simulate

```{r assemble_stan_data_function}
assemble_stan_data <- function(prices, predictors, future_predictors, seasonality) compose_data(prices, 
                          x=predictors, 
                          x_predictive = future_predictors,
                          N_periods = max(prices$period),
                          N_features = ncol(predictors),
                          periods_to_predict = params$periods_to_predict, 
                          # parameters controlling the model 
                          p = params$p, 
                          q = params$q, 
                          ar = params$ar, 
                          period_scale = params$period_scale, 
                          # Parameters controlling hierarchical shrinkage
                          nu = params$nu, 
                          m0 = params$m0,
                          seasonality,
                          s = seasonality$s,
                          N_seasonality = nrow(seasonality),
                          .n_name = n_prefix("N"))
```

```{r make_stan_data}
prices_gathered <- prices %>%
  gather(key="series", value="log_price", -period) %>%
  mutate(price = exp(log_price) - 1) %>%
  dplyr::select(-log_price) %>%
  arrange(period, series) %>%
  mutate(id = 1:n())

sampled_prices_for_stan <- data.frame(
  period = sample(params$P, params$N, replace=T), 
  series = sample(unique(prices_gathered$series), params$N, replace=T)
) %>% 
  inner_join(prices_gathered) %>%
  mutate(
    y = rnorm(n(), mean=price, sd=50)
  ) %>%
  dplyr::filter(y > 0) %>%
  mutate(
    weight = 1,
    id = 1:n()
  )


seasonality <- data.frame(
  s = c(4, 2)
) %>% mutate(
  seasonality = paste("seasonality", 1:n(), sep="_")
)

predictors <- matrix(rnorm(params$P * params$F), ncol=params$F)
future_predictors <- matrix(rnorm(params$periods_to_predict * params$F), ncol=params$F)

sampled_stan_data <- assemble_stan_data(dplyr::select(sampled_prices_for_stan, -id), predictors, future_predictors, seasonality)

exact_stan_data <- prices_gathered %>% 
  dplyr::filter(period <= params$P) %>% 
  rename(y=price) %>% 
  mutate(weight = 1) %>% 
  assemble_stan_data(predictors, future_predictors, seasonality)

prices_gathered %<>% rename(y=price)
```

```{r select_price_set}
exact <- ! as.logical(params$use_sampled)

if (exact) {
  stan_data <<- exact_stan_data
  price_set <<- prices_gathered
} else {
  stan_data <<- sampled_stan_data
  price_set <<- sampled_prices_for_stan 
}
```


```{r make_model}
model <- stan_model("./mbsts.stan")
```

```{r sample}
samples <- sampling(model, data=stan_data, chains=2, iter=2000, cores=2,
                   # control=list(adapt_delta=0.95, max_treedepth=15)
                    ) %>% recover_types(price_set)
```

## Inspect Model

### Prediction Accuracy

```{r recover_y_hat}
y_hat <- samples %>% gather_draws(log_y_hat[id]) %>%
  mutate(.value = exp(.value) - 1)
```

```{r residuals}
y_hat %>% 
  dplyr::select(id, .value) %>%
  inner_join(price_set) %>% 
  mutate(
    error = .value - y
  ) %>%
  group_by(id, series) %>%
  summarize(
    mean_error = mean(error),
    rmse = sqrt(mean(error^2)), 
    sd_y_hat = sd(.value)
  ) %>% 
  ungroup() %>%
  dplyr::select(series, mean_error, rmse, sd_y_hat) %>% 
  gather(key="metric", value="value", -series) %>% 
  ggplot(aes(x = value, fill=series)) +
  geom_histogram(bins=40, position="identity", alpha = 1/params$S) + 
  facet_grid(series ~ metric, scales="free") +
  theme_minimal() +
  ggtitle("Residuals")
```

```{r visualize_predictions}
price_set %>% dplyr::select(id, y, series) %>%
  inner_join(y_hat %>% 
               group_by(id) %>%
               summarize(y_hat = mean(.value))) %>%
  ggplot(aes(x = y, y=y_hat)) +
  geom_point(size=0.2, alpha=0.2) +
  facet_wrap(~ series) +
  scale_x_continuous(limits=c(0, NA)) + 
  scale_y_continuous(limits=c(0, NA)) + 
  annotate("segment", x = 0, y = 0, xend=max(price_set$y), yend=max(price_set$y), color="red", size=0.5, alpha=0.5) +
  theme_minimal() + 
  ggtitle("Prices vs. Mean Predictions")
```

### Visualize Time Series

```{r recover_time_series}
periodic_price_hat <- samples %>% gather_draws(log_prices_hat[period, series])
```

```{r time_series_by_chain}
mean_periodic_price_hat <- periodic_price_hat %>%
  group_by(period, series) %>%
  summarize(
    y_hat = exp(mean(.value))
  ) %>%
  mutate(.chain = as.character("mean_hat"))

periodic_price_hat %>%
  group_by(period, series, .chain) %>%
  summarize(
    y_hat = exp(mean(.value))
  ) %>%
  mutate(.chain = as.character(.chain)) %>%
  bind_rows(prices_gathered %>% mutate(.chain="gen") %>% rename(y_hat=y), mean_periodic_price_hat) %>% 
  mutate(alpha = case_when(
    .chain %in% c("gen", "mean_hat") ~ .8, 
    TRUE ~ .2
  )) %>%
  ggplot(aes(x = period, y = y_hat, color=series, linetype=.chain, alpha=I(alpha))) +
  geom_line(size=0.5) +
  theme_minimal() +
  ggtitle("Reconstruction of Time Series By Chain")
```

### Visualize Price Forecast

```{r gather_price_forecast}
price_forecast <- samples %>% 
  gather_draws(log_predicted_prices[period, series]) 
```

```{r visualize_price_forceast}
true_future <- prices_gathered %>%
  dplyr::filter(period > params$P) %>%
  mutate(period = period - params$P)
  

price_forecast %>% 
  mutate(price = exp(.value)) %>%
  group_by(series) %>% 
  ggplot(aes(x = period, y=price, group=series, color=series)) +
  stat_lineribbon(.width=c(0.2, 0.3, 0.66), alpha=0.3, color="darkblue", size=0.5) +
  geom_line(data=true_future, aes(x=period, y=y, color=series)) +
  scale_fill_brewer("Confidence", palette="Blues") +
  #scale_y_log10() +
  theme_minimal()
```

### Visualize Period Components

```{r recover_components}
combined_components <- samples %>%  gather_draws(delta[period, series], tau_s[seasonality][period, series], omega[period, series], epsilon[period, series], xi[period, series])  %>% 
  mutate(
    component = case_when(
      .variable == "delta" ~ "trends", 
      .variable == "epsilon" ~ "innovations", 
      .variable == "tau_s" ~ paste("seasonality", seasonality, sep="_"), 
      .variable == "omega" ~ "cyclicality", 
      .variable == "xi" ~ "predictors"
    )
  )

components_mean <- combined_components %>%
  ungroup() %>%
  group_by(period, series, component) %>%
  summarize(.value = mean(.value)) %>% 
  mutate(.chain = "mean_hat")

components_mean %>%
  ggplot(aes(x = period, y = .value, color=component)) +
  facet_grid(series ~ ., scales="free_y") +
  geom_line(size=0.2) +
  theme_minimal() +
  ggtitle("Components of Price Movements (Means)")
```

```{r view_components_by_chain}
components_by_chain <- combined_components %>%
  ungroup() %>%
  group_by(period, series, component, .chain) %>%
  summarize(.value = mean(.value)) %>%
  mutate(.chain = as.character(.chain))

bind_rows(components_by_chain, components_mean) %>%
  mutate(alpha = case_when(
    .chain == "mean_hat" ~ 1, 
    TRUE ~ 0.2
  )) %>%
  ggplot(aes(x = period, y = .value, color=component, linetype=factor(.chain), alpha=I(alpha))) +
  facet_grid(series ~ ., scales="free_y") +
  geom_line(size=0.2) +
  #scale_x_continuous(limits=c(0, 80)) +
  theme_minimal() +
  ggtitle("Components of Price Movements (By Chain)")
```

### Visualize Cyclicality

```{r cyclicality}
cylicality_hat <- samples %>% gather_draws(lambda[series], rho[series])
```


```{r view_cyclicality}
true_cyclicality <- data.frame(
  lambda = lambda, 
  rho = rho, 
  series = sort(unique(cylicality_hat$series))
) %>%
  gather(key=".variable", value=".value", -series)

cylicality_hat %>% 
  ggplot(aes(x = .value)) + 
  geom_histogram(bins=60) +
  geom_vline(data=true_cyclicality, aes(xintercept=.value), color="blue", size=0.5) +
  facet_grid(series ~ .variable, scales="free") +
  theme_minimal() + 
  ggtitle("Estimates of Cycle Frequency and Damping")
```

### Visualize Trend Correlations

```{r recover_return_correlations}
trend_corr_hat <- samples %>% gather_draws(trend_corr[series1, series2])

true_trends <- omega_trend %>%
  data.frame() %>%
  set_colnames(1:ncol(omega_trend)) %>%
  mutate(series1 = 1:n()) %>%
  gather(key="series2", value=".value", -series1)
```

```{r show_trend_corr}
trend_corr_hat %>%
  dplyr::filter(series1 != series2) %>%
  ggplot(aes(x = .value)) +
  geom_histogram(bins=100) +
  geom_vline(data=data.frame(xintercept=0), aes(xintercept=xintercept), color="red", size=0.2) +
  geom_vline(data=true_trends, aes(xintercept=.value), color="blue", size=0.2) +
  facet_grid(series1 ~ series2) +
  theme_minimal() + 
  ggtitle("Trend Correlations")
```

### Visualize Innovation Correlations

```{r recover_innovation_correlations}
innovation_corr_hat <- samples %>% gather_draws(innovation_corr[series1, series2])

true_innovations <- omega_epsilon %>%
  data.frame() %>%
  set_colnames(1:ncol(omega_trend)) %>%
  mutate(series1 = 1:n()) %>%
  gather(key="series2", value=".value", -series1)
```

```{r show_innovation_corr}
innovation_corr_hat %>%
  dplyr::filter(series1 != series2) %>%
  ggplot(aes(x = .value)) +
  geom_histogram(bins=100) +
  geom_vline(data=data.frame(xintercept=0), aes(xintercept=xintercept), color="red", size=0.2) +
  geom_vline(data=true_innovations, aes(xintercept=.value), color="blue", size=0.2) +
  facet_grid(series1 ~ series2) +
  theme_minimal() + 
  ggtitle("Innovation Correlations")
```

### Visualize Shrinkage Parameters

```{r recover_shrinkage_parameters}
shrinkage_hat <- samples %>% gather_draws(beta_ar_hs[feature, series], beta_p_hs[feature, series], beta_q_hs[feature, series], beta_xi_hs[feature, series]) 

shrinkage_hat %>% 
  ungroup() %>%
  mutate(.variable = str_replace(.variable, "_hs", "")) %>%
  ggplot(aes(x = .value)) +
  geom_histogram(bins=60) +
  geom_vline(data=data.frame(xintercept=0), aes(xintercept=xintercept), color="red", size=0.2) +
  facet_grid(.variable + feature ~ series, scales ="free_x") +
  theme_minimal()
```

### Visualize Coefficients

```{r visualize_coefficients}
coefficients_hat <- samples %>% gather_draws(beta_ar[feature, series], beta_xi[feature, series], 
                                             beta_p[feature, series], beta_q[feature, series])

coefficients_hat %>%
  ggplot(aes(x = .value)) +
  geom_histogram(bins=60) +
  facet_grid(series ~ .variable + feature, scales="free_x") +
  theme_minimal() +
  ggtitle("Estimated Coefficients")
```

### Visualize Volatilities and Intercepts

```{r visualize_volatilities}
volatilities_hat <- samples %>% gather_draws(theta_ar[series], alpha_ar[series], theta_cycle[series], theta_season[seasonality][series], omega_garch[series]) %>%
  ungroup() %>% 
  mutate(
    component = case_when(
      .variable == "theta_season" ~ paste("theta_season", seasonality, sep="_"),
      TRUE ~ .variable
    )
  )

volatilities_hat %>% 
  ggplot(aes(x = .value)) +
  geom_histogram(bins=60) +
  facet_grid(series ~ component, scales="free") +
  theme_minimal() +
  ggtitle("Estimated Volatilities and Baselines")
```

# DONE